### PR TITLE
Add support for ERA5 back extension until 1950 in v0.2

### LINKED ISSUE #105: ERA5 back extension in v0.2
Allow for the back extension of ERA5 in upcoming v0.2 (#104)

### PR DESCRIPTION
**Pull request by fneum**
Closes #105.

## Change proposed in this Pull Request

Same as #104 but for version 0.2.

Add support for ERA5 back extension until 1950.

## Description

Change of product name if requested year is 1978 or below.

This workaround will likely be necessary until the end of 2021 for when the merge of the ERA5 products pre and post 1979 was announced: https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-preliminary-back-extension?tab=overview

## Motivation and Context

Feature was temporarily disabled when transitioning to v0.2, see #105.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] I locally ran `pytest` inside the repository and no unexpected problems came up.
- [ ] I have adjusted the docstrings in the code appropriately.
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have added newly introduced dependencies to `environment.yaml` file.
- [ ] I have added a note to release notes `doc/release_notes.rst`.

### CODE REVIEW

**Comment by fneum** [comment]
No worries, just thought to add it as it's mentioned in the paper.

There's one error remaining in the last row of `get_data()` when there is an overlap of the products (e.g. slice(1978-12, 1979-02))

**Comment by fneum** [comment]
> There's one error remaining in the last row of `get_data()` when there is an overlap of the products (e.g. slice(1978-12, 1979-02))

It is not the overlap that causes the problem, but the 'runoff' variable at the beginning of 1979 (another issue).

**Comment by euronion** [comment]
@fneum  The ERA5 backextension now seems to have moved from being preliminary to being considered stable. It should now be part of the standard `ERA5` data in CDS. Could you try downloading an ERA5 cutout from before 1979 without this PR and see if it already works?

If yes then this PR would now be obsolete.

**Comment by fneum** [comment]
Ah, that must have been very recent. When I checked last week it was still from 1979 onwards, now 1959 onwards (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview). Still 1950-1958 missing.

On change remains necessary:

https://github.com/PyPSA/atlite/blob/master/atlite/gis.py#L73

Limits the allowed time frame to dates from 1979 onwards. Can make a separate PR.

**Comment by euronion** [comment]
Yes, the announcement came last Thursday about ERA5 now including the backextension.

Separate PR would be appreciated :)

**Comment by FabianHofmann** [comment]
closed in favor of #247

**Pull request closed without merging**
