### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by FabianHofmann**
Addresses #157

### CODE REVIEW

**Comment by euronion** [comment]
What about : https://atlite.readthedocs.io/en/latest/contributing.html ?

I don't see much of a content overlap, but we should not have two cages for the one bird.

What I think we could do:
- Link to the "How to contribute" in the `Readme.md` and in the Issue/PR template
- Combine your PR w/ the `Contributing` in RTD
- I'll have a look at the code style issue (related to #153 )

What do you think?

**Comment by FabianHofmann** [comment]
But this is another topic right? The code of conduct is rather a general behavior guideline. In https://github.com/PyPSA/atlite/community it is listed separately from the contributing guideline (this is where I got the idea from). I mean we don't have to include it at all, if there is no need (good-practise packages like [xarray](https://github.com/pydata/xarray) have it though)

**Comment by euronion** [comment]
Short/formal remarks:
- For me "How to contribute" and "how to behave" are closely related in our case.
- IMHO it should in any case be part of the RTD / linked in the contributions page.
- License missing (for REUSE compliance / license by Contributor Convenant Code of Conduct, i.e. CC-BY-4.0 Coraline Ada Ehmke, Copyright 2014)

Longer remarks:
- I never thought of including a Code of Conduct until now. I like the principle idea and wonder whether this COC fits our bill (maybe a shorter version of the same would fit better or a different one?)
- Some parts of the COC do not seem to fit: Like enforcement guidelines, Scope or Enforcement Responsibilities?
- Under "Enforcement" the original has a `[INSERT CONTACT METHOD]` which is missing in your PR and would need to be filled.

**Comment by FabianHofmann** [comment]
I definitely agree with your points. I close this PR and as soon as we see real need for it, we reopen modify...

**Pull request closed without merging**
