### PR TITLE
Update config system to use a object rather than a module.

### PR DESCRIPTION
**Pull request by euronion**
> Implementing https://github.com/PyPSA/atlite/issues/45

The config system now uses a config object, located in the module "config".
The parent class is atlite.config.Config, access to the configuration is now achieved via atlite.config.config .
Getters and setters are implemented, the callback function for update hooks is mostly working, except for when the object atlite.config.config is overwritten directly with a new Config object.

Since we can now use getters and setters, manual calls for resolving the (relative) file path are obsolete and now automatically handled by the `config` object.

I could not figure out two problems related to direct overwrites of the `atlite.config.config` object, i.e. by
```
atlite.config.config = Config()
```
1. How to call the `_UPDATE_HOOKS` (listener pattern on module variable)
2. How to use the config in other modules as
```
from .config import config
...
config.windturbine_dir
```
without comprimising the integrity in the case of a direct assignment above.
The current version works in this case, i.e. the complexity
```
from . import config
....
config.config.windturbine_dir
```
is required for covering the case that the `config` object changes.

### CODE REVIEW

**Comment by fneum** [comment]
@euronion this relevant or necessary for `v0.2`?

**Comment by euronion** [comment]
It was, not sure if the changes by Jonas made it obsolete - I'll have to check it during review.

**Comment by coroa** [comment]
Obsolete

**Comment by coroa** [comment]
No config system, instead.

**Pull request closed without merging**
