### PR TITLE
Download data simultaneously and cache files

### PR DESCRIPTION
**Pull request by yndevops2**
This update speeds up downloading ERA5 data by letting you download multiple files at once. It also adds caching for downloaded data and a progress bar to track the download status.

### CODE REVIEW

**Comment by lkstrp** [comment]
Hey @yndevops2,
all merging issues should be resolved now. Sorry for the late response, this will be better from now on. You don't need to create an extra issue for those things, just ping me here.

Please give me a bit more time to review your PR. I will test it soon. Thank you !

**Review by yndevops2 — COMMENTED** [review]
Still issue with codecov.
Could you please help me?

**Comment by lkstrp** [comment]
There have been some changes to the tests which might messed up your report. But that should be fine now. 
To resolve the failing Code Cov you need to provide tests for your newly created functions. Check the full [Codecov Report](https://app.codecov.io/gh/PyPSA/atlite/pull/385) which points you to which lines need additional tests. You can implement them in `/test` (we use [pytest](https://docs.pytest.org/en/stable/)).

**Comment by yndevops2** [comment]
This is first time for the CodeCov.
So if you can help me for that, that would be great help for me!!!!

**Pull request closed without merging**
