### PR TITLE
fix exclusion for non overlapping geometries

### PR DESCRIPTION
**Pull request by FabianHofmann**
and add convenience functions to ExclusionContainer class

## Change proposed in this Pull Request

In recent eligibility calculations in pypsa-eur we saw bugs coming up, when the raster and the geometries are not overlapping. This changes fix this issue. 

Additionally this change introduces two new functions to the `ExclusionContainer` class that ease the inspection of excluded areas in a geometry. 

The example notebook for show-casing the land-use calculation was update to show the new functions.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] I locally ran `pytest` inside the repository and no unexpected problems came up.
- [x] I have adjusted the docstrings in the code appropriately.
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have added newly introduced dependencies to `environment.yaml` file.
- [ ] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution

### CODE REVIEW

**Review by fneum — APPROVED** [review]
I like the new functions!

**Comment by euronion** [comment]
Nice. Did you intentionally remove ~Macedonia~ North Macedonia from all examples and plots?

**Comment by FabianHofmann** [comment]
> Nice. Did you intentionally remove ~Macedonia~ North Macedonia from all examples and plots?

Not really, was there a renaming? It is still in the list of selected countries...

**Comment by euronion** [comment]
Yes, the country was officially renamed in 2019. Probably the name change took some time to propagate to the datasets.

**Pull request merged**
