### PR TITLE
update dask requirements, remove scm requirement

### LINKED ISSUE #191: Could be possible to allow again more recent versions of `dask>=0.18.1`
https://github.com/PyPSA/atlite/blob/e1127d9946fdff4e5c2f63a2cb674147817d3ca4/setup.py#L35

https://github.com/dask/dask/issues/7583

https://docs.dask.org/en/stable/changelog.html#id4

https://github.com/dask/dask/pull/8040

### LINKED ISSUE #192: Local installation with `pip -e` fails
Local installation of atlite with `pip -e .` fails with error.

`  /home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.            `

## Expected Behavior
`atlite` installed editable by pip from local folder.

## Error Message

Full error message
```
$ pip install -e .
Obtaining file:///home/pypsa/share/GitHub/atlite_development
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pypsa/miniconda3/envs/pypsa-eur/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pypsa/share/GitHub/atlite_development/setup.py'"'"'; __file__='"'"'/home/pypsa/share/GitHub/atlite_development/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a29_jm2a                                                                                                                                                                                           
       cwd: /home/pypsa/share/GitHub/atlite_development/                                                                                                                                     
  Complete output (29 lines):                                                                                                                                                                
  /home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.                                                                                                                                                        
    warnings.warn(                                                                                                                                                                           
  Traceback (most recent call last):                                                                                                                                                         
    File "<string>", line 1, in <module>                                                                                                                                                     
    File "/home/pypsa/share/GitHub/atlite_development/setup.py", line 13, in <module>                                                                                                        
      setup(                                                                                                                                                                                 
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/__init__.py", line 158, in setup                                                                      
      _install_setup_requires(attrs)                                                                                                                                                         
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in _install_setup_requires                                                    
      dist.fetch_build_eggs(dist.setup_requires)                                                                                                                                             
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs                                                               
      resolved_dists = pkg_resources.working_set.resolve(                                                                                                                                    
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve                                                                 
      dist = best[req.key] = env.best_match(                                                                                                                                                 
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match                                                             
      return self.obtain(req, installer)                                                                                                                                                     
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain                                                                 
      return installer(requirement)                                                                                                                                                          
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg                                                                
      return fetch_build_egg(self, req)                                                                                                                                                      
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/installer.py", line 80, in fetch_build_egg                                                            
      wheel.install_as_egg(dist_location)                                                                                                                                                    
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/wheel.py", line 95, in install_as_egg                                                                 
      self._install_as_egg(destination_eggdir, zf)                                                                                                                                           
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/wheel.py", line 103, in _install_as_egg                                                               
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)                                                                                                                    
    File "/home/pypsa/miniconda3/envs/pypsa-eur/lib/python3.8/site-packages/setuptools/wheel.py", line 124, in _convert_metadata                                                             
      os.mkdir(destination_eggdir)                                                                                                                                                           
  FileExistsError: [Errno 17] File exists: '/home/pypsa/share/GitHub/atlite_development/.eggs/setuptools_scm-6.3.2-py3.8.egg'                                                                
  ----------------------------------------                                                                                                                                                   
WARNING: Discarding file:///home/pypsa/share/GitHub/atlite_development. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Your Environment

* The `atlite` version used: Latest (commit e1127d9946fdff4e5c2f63a2cb674147817d3ca4)
* How you installed `atlite` (`conda`, `pip` or `github`): - (Installation fails)
* Operating System: Linux
* My environment:
<details>
      <summary>(output of `conda list`)</summary>
```
# packages in environment at /home/pypsa/miniconda3/envs/pypsa-eur:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
amply                     0.1.4                      py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.4.1            py38h578d9bd_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.26           h06a4308_2  
cartopy                   0.20.1           py38h4de569d_2    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.14.6           py38h3931269_1    conda-forge
cftime                    1.5.1.1          py38h6c62de6_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
coincbc                   2.10.5               hcee13e7_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
conda                     4.10.3           py38h578d9bd_2    conda-forge
conda-package-handling    1.7.3            py38h497a2fe_0    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
countrycode               0.2                      pypi_0    pypi
cryptography              35.0.0           py38h3e25421_1    conda-forge
curl                      7.79.1               h2574ce0_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
dask                      2021.3.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.3.1           pyhd8ed1ab_0    conda-forge
datrie                    0.8.2            py38h497a2fe_2    conda-forge
debugpy                   1.4.1            py38h709712a_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2021.4.1         py38h578d9bd_1    conda-forge
docutils                  0.18             py38h578d9bd_0    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
entsoe-py                 0.3.7              pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0            py38h06a4308_0  
filelock                  3.3.2              pyhd8ed1ab_0    conda-forge
freetype                  2.11.0               h70c0345_0  
fsspec                    2021.10.1          pyhd8ed1ab_0    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geopy                     2.2.0              pyhd8ed1ab_0    conda-forge
geos                      3.10.0               h9c3ff4c_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
gitdb                     4.0.7              pyhd3eb1b0_0  
gitpython                 3.1.24             pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.14.6             pyhd8ed1ab_0    conda-forge
hvplot                    0.7.3              pyh6c4a22f_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.2                pyhd3eb1b0_0  
importlib-metadata        4.8.1            py38h578d9bd_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_0    conda-forge
ipykernel                 6.4.2            py38he5a9106_0    conda-forge
ipython                   7.29.0           py38he5a9106_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                4.1.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_0    conda-forge
kiwisolver                1.3.2            py38h1fd1430_0    conda-forge
krb5                      1.19.2               hcc1bbae_2    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcurl                   7.79.1               h2574ce0_1    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20210714         h7f8727e_0  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libwebp                   1.2.1                h3452ae3_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
locket                    0.2.1            py38h06a4308_1  
lxml                      4.6.3            py38hf1fe3a4_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.17.0           py38h2aa5da1_0    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib-base           3.4.3            py38hf4fb855_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
memory_profiler           0.58.0                     py_0    conda-forge
mock                      4.0.3            py38h578d9bd_1    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8           nompi_py38h2823cc8_100    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numexpr                   2.7.3            py38h51da96c_0    conda-forge
numpy                     1.21.3           py38he2449b9_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py38h43a58ef_0    conda-forge
panel                     0.12.4             pyhd8ed1ab_0    conda-forge
param                     1.12.0             pyh6c4a22f_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1002    conda-forge
pillow                    8.4.0            py38h5aabda8_0  
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
powerplantmatching        0.4.8              pyhd8ed1ab_0    conda-forge
proj                      8.1.1                h277dcde_2    conda-forge
prompt-toolkit            3.0.21             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulp                      2.5.1            py38h578d9bd_0    conda-forge
pycosat                   0.6.3           py38h497a2fe_1006    conda-forge
pycountry                 20.7.3             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyomo                     6.1.2            py38h709712a_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.4              pyhd8ed1ab_0    conda-forge
pyproj                    3.2.1            py38h80797bf_2    conda-forge
pypsa                     0.18.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pytables                  3.6.1            py38hdb04529_4    conda-forge
python                    3.8.10          hb7a2778_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.1.0              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h497a2fe_0    conda-forge
pyzmq                     22.3.0           py38h2035c66_0    conda-forge
ratelimiter               1.2.0           py38h32f6830_1001    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.100         py38h27cfd23_0  
scikit-learn              1.0.1            py38hacb3eff_1    conda-forge
scipy                     1.7.1            py38h56a6a73_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                58.3.0           py38h578d9bd_0    conda-forge
shapely                   1.8.0            py38hf7953bd_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
snakemake-minimal         6.7.0              pyhdfd78af_0    bioconda
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.2.1              pyhd3eb1b0_0  
sqlite                    3.36.0               h9cd32fc_2    conda-forge
statsmodels               0.13.0           py38h6c62de6_0    conda-forge
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
toposort                  1.7                pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tsam                      1.1.0                    pypi_0    pypi
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vresutils                 0.3.1                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.13.3           py38h497a2fe_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```
    </details>

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes #191 
Closes #192 

## Change proposed in this Pull Request

Update dask requirements, set scm requirement through pyproject.toml as recommended by https://pypi.org/project/setuptools-scm/ 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] I locally ran `pytest` inside the repository and no unexpected problems came up.

### CODE REVIEW

**Comment by euronion** [comment]
The CI test's shouldn't take >2h, right? Something seems off.

**Comment by euronion** [comment]
Other than that, `pip install -e .` and `conda develop .` seem to work again.
Not sure how to test for the `xarray` problem we had in the past - for now the memory footprint seems fine.

**Comment by euronion** [comment]
Can you check on the CI test @FabianHofmann ?

**Comment by FabianHofmann** [comment]
The long duration came from CDS Server being not responsive yesterday. Now the tests run through smoothly. When I checked the memory usage for large cutouts, the performance is as to expect (no explosion of memory).

**Pull request merged**
